var context = { dynamic: 'this is dynamic' };

var things = [
    z().span().text('wat'),
    z().span().text('yolo'),
    z().span().text('gtfo')
];

var html = 
    z()
        .div({ class: 'header' })
            .elements([
                z().element('h1', { class: 'title' }).text('This is generated by Zappa !'),
                z().div({class: 'body'}).elements(things)
            ])
        .value();

document.querySelector('.container').appendChild(html);
